# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Royalty_UI' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

#Pods for Royalty_UI
	pod 'CSV.swift', '~> 1.1'
end